language: erlang
dist: trusty

before_install:
  - curl -O https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-6.5.4.deb && sudo dpkg -i --force-confnew elasticsearch-6.5.4.deb && sudo service elasticsearch restart

script:
   - make
   - make test
   - ./rebar3 coveralls send

otp_release:
   - 20.1
   - 20.0
   - 19.2

